### ISSUE TITLE
Filter out poor datasets before creating a packagezip

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-packagezip#7]
If the zip file isn't going to contain any useful data it would be good to not create the zip file.

**Comment by morty** [comment]
Decided to generate the zip file whatever, but put a warning if there are no real data files only HTML, API, WMS etc

**Comment by davidread** [comment]
I suggest that "no data" means: HTML, API, SPARQL, WMS, WFS, as determined by QA.

**Comment by rossjones** [comment]
In the index.html we should have:

* (Not a useful format) ->Resource is not included in the zip because the detected format 'X' suggests it is n0t data
* (Not in archive) -> Resource is not included in the zip because the link is broken 
* (Useful and in archive) -> Resource was archived on dd/mm/yyyy. 

Remove cache_filepath from datapackage.
